### ISSUE TITLE
List all resources in your organization error not very friendly

### ISSUE THREAD

**Issue by ran-huang** [Oreoxmt/tidbcloudy#3]
Getting this when running the sample code of `List all resources in your organization` in README. 

Is this expected?

<img width="899" alt="image" src="https://user-images.githubusercontent.com/59654584/184569373-54d945d7-79bc-4b2b-bfd3-6a2a8ee339cc.png">

Maybe we should add some error handling logic in `iter_backups` so users don't get to see `traceback (most recent call last)`, which is quite intimidating to me. (I'm not sure though)

**Comment by Oreoxmt** [comment]
> Getting this when running the sample code of `List all resources in your organization` in README.

For a Developer Tier cluster, you can add the following condition to escape the error:

```python
for project in api.iter_projects():
    print(project)
    for cluster in project.iter_clusters():
        print(cluster)
        if cluster._cluster_type != "DEVELOPER":
            for backup in cluster.iter_backups():
                print(backup)
    for restore in project.iter_restores():
        print(restore)
```

I will update the code sample to the following after closing the [issue/5](https://github.com/Oreoxmt/tidbcloudy/issues/5):

```python
for project in api.iter_projects():
    print(project)
    for cluster in project.iter_clusters():
        print(cluster)
        if cluster.cluster_type != "DEVELOPER":
            for backup in cluster.iter_backups():
                print(backup)
    for restore in project.iter_restores():
        print(restore)
```

> Maybe we should add some error handling logic in iter_backups so users don't get to see traceback (most recent call last), which is quite intimidating to me. (I'm not sure though)

All errors should be handled by the user.

**Comment by Oreoxmt** [comment]
@ran-huang The *List all resources ...* code sample is updated in [`examples/0_list_resources.py`](https://github.com/Oreoxmt/tidbcloudy/blob/f072d1a3d7c4f9e31e13715352a715143687f3b7/examples/0_list_resources.py), and you can run it directly.
